version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: $WP_DOMAIN_db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes: 
      - /home/qw-_userdomain/dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      backend:
    user: "_userid:_groupid"
    mem_limit: _memlimit
    cpus: _cpulimit
  wordpress:
    depends_on: 
      - db
    image: wordpress:6.2-php8.2
    container_name: $WP_DOMAIN_wp
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    ports:
      - "10.89.1.2:_random80:80"
    volumes:
      - /home/qw-_userdomain/wpdata:/var/www/html
    networks:
      backend:
    user: "_userid:_groupid"
    mem_limit: _memlimit
    cpus: _cpulimit
  filebrowser:
    container_name: $WP_DOMAIN_filebrowser
    image: filebrowser/filebrowser
    networks:
      backend:
    ports:
      - "10.89.1.2:_random81:80"
    volumes:
      - /home/qw-_userdomain/wpdata:/srv
      - ./config:/config
    restart: always 

volumes:
  wordpress:
  dbdata:

networks:
  backend:
