version: '2.4'

services:
  db:
    image: mysql:8.0.32
    container_name: $WP_DOMAIN_db
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes: 
      - /home/_userdomain/dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      backend:
    user: "_userid:_groupid"
    mem_limit: _memlimit
    cpus: _cpulimit
 #   labels:
 #     io.portainer.accesscontrol.teams: admin
  wordpress:
    depends_on: 
      - db
    image: wordpress:6.2-php8.2
    container_name: $WP_DOMAIN_wp
    restart: always
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    ports:
      - "_ipprivate_node:_random80:80"
    volumes:
      - /home/_userdomain/sitedata:/var/www/html
      - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini
    networks:
      backend:
    user: "_userid:_groupid"
    mem_limit: _memlimit
    cpus: _cpulimit
#    labels:
#      io.portainer.accesscontrol.teams: admin
  filebrowser:
    depends_on:
      - wordpress
    restart: always
    container_name: $WP_DOMAIN_filebrowser
    image: filebrowser/filebrowser:v2-s6
    networks:
      backend:
    ports:
      - "_ipprivate_node:_random81:80"
    volumes:
      - /home/_userdomain/sitedata:/srv
      - ./config:/config
    mem_limit: _memlimit
    cpus: _cpulimit
    environment:
      - PUID=_userid
      - PGID=_groupid
#    labels:
#      io.portainer.accesscontrol.teams: admin
  phpmyadmin:
    depends_on:
      - db
    restart: always
    image: phpmyadmin:5.2.1-fpm-alpine
    container_name: $WP_DOMAIN_pma
    environment:
       - PMA_HOST=db
       - UPLOAD_LIMIT=100M
       - PMA_PMADB=pmadb
    ports:
      - "_ipprivate_node:_random82:80"
    networks:
      backend:
    mem_limit: 0.2G
    cpus: 1.0
    user: "_userid:_groupid"
    volumes:
      - /home/_userdomain/pma/config.secret.inc.php:/etc/phpmyadmin/config.secret.inc.php
      - /home/_userdomain/pma/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
      - /home/_userdomain/pma/config.inc.php:/etc/phpmyadmin/config.inc.php:ro
#    labels:
#      io.portainer.accesscontrol.teams: admin

volumes:
  wordpress:
  dbdata:
  pma:

networks:
  backend:
