version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: $WP_DOMAIN_db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes: 
      - /home/_userdomain/dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network
    user: "_userid:_groupid"
    mem_limit: _memlimit
    cpus: _cpulimit
  wordpress:
    depends_on: 
      - db
    image: wordpress:6.2.0-php8.2-fpm-alpine
    container_name: $WP_DOMAIN_wp
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - /home/_userdomain/wpdata:/var/www/html
    networks:
      - app-network
    user: "_userid:_groupid"
    mem_limit: _memlimit
    cpus: _cpulimit
  webserver:
    depends_on:
      - wordpress
    image: nginxinc/nginx-unprivileged
    container_name: $WP_DOMAIN_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /home/_userdomain/wpdata:/var/www/html
      - /home/_userdomain/nginx-conf:/etc/nginx/conf.d
      - /home/_userdomain/certbot:/etc/letsencrypt
    networks:
      - app-network
    user: "_userid:_groupid"
    mem_limit: _memlimit
    cpus: _cpulimit
  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: $WP_DOMAIN_certbot
    volumes:
      - /home/_userdomain/certbot:/etc/letsencrypt
      - /home/_userdomain/wpdata:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email teknis@qwords.co.id --agree-tos --no-eff-email --staging -d _domain -d www._domain
    
volumes:
  certbot-etc:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge  
